services:
  # PostgreSQL
  postgres-container:
    container_name: postgres-container
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/data/postgres
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin-container:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - postgres-container

  # MySQL
  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network
    restart: unless-stopped

  phpmyadmin-container:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - mysql-network
    restart: unless-stopped
    depends_on:
      - mysql-container

  # SQL Server
  mssql-container:
    container_name: mssql-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mssql-network
    restart: unless-stopped

  # MongoDB
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network
    restart: unless-stopped

  mongo-express-container:
    container_name: mongo-express-container
    image: mongo-express:latest
    ports:
      - "${ME_CONFIG_PORT}:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${ME_CONFIG_MONGODB_AUTH_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${ME_CONFIG_MONGODB_AUTH_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    networks:
      - mongo-network
    restart: unless-stopped

  # Cassandra
  cassandra-container:
    container_name: cassandra-container
    image: cassandra:4.1
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_DC: ${CASSANDRA_DC}
      CASSANDRA_RACK: ${CASSANDRA_RACK}
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_PASSWORD_SEEDER: "true"
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra-network
    restart: unless-stopped

  # Oracle
  oracle-container:
    container_name: oracle-container
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "${ORACLE_PORT}:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - oracle-network
    restart: unless-stopped
  
  # Neo4j
  neo4j-container:
    container_name: neo4j-container
    image: neo4j:5.23.0-enterprise
    restart: unless-stopped
    ports:
      - "${NEO4J_PORT}:7474"  
      - "${NEO4J_BOLT_PORT}:7687"  
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc","bloom"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms.memory.heap.max_size=2G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/var/lib/neo4j
    networks:
      - neo4j-network

networks:
  postgres-network:
    driver: bridge
  mysql-network:
    driver: bridge
  mssql-network:
    driver: bridge
  mongo-network:
    driver: bridge
  cassandra-network:
    driver: bridge
  oracle-network:
    driver: bridge
  neo4j-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  mysql_data:
  mssql_data:
  mongodb_data:
  cassandra_data:
  oracle_data:
  neo4j_data: