services:
  neo4j-container:
    container_name: neo4j-container
    image: neo4j:5.23.0-enterprise
    restart: unless-stopped
    ports:
      - "${NEO4J_PORT}:7474"  
      - "${NEO4J_BOLT_PORT}:7687"  
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc","bloom"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms.memory.heap.max_size=2G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j:/var/lib/neo4j
    networks:
      - neo4j

networks:
  neo4j:
    driver: bridge

volumes:
  neo4j:
